# Generated by Django 4.1.7 on 2023-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.IntegerField()),
                ('content', models.TextField(max_length=500)),
            ],
        ),
    ]
